[package]
name = "soy_native"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "soy_native"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.24.0"
rocksdb = {version = "0.18.0", features = ["multi-threaded-cf"]}